### ISSUE TITLE
[BE Tutorial] App 이웅재의 1장 생각해보기

### ISSUE THREAD

**Issue by wjlee611** [GDSC-Kwangwoon-University/BE-TUTORIAL#1]
## 🔍 생각해보기

1. spring initializer에서 java 11을 지원하지 않기 때문인거 같아요
2. react, next와 같이 spring boot web 프레임워크의 기본 시작 페이지가 index.html로 설정되어 있기 때문인거 같아요
3. 서버에 접근 가능한 포트 번호를 의미하며, 바꿀 수 있는 방법은 `resources/application.properties`에 `server.port = 12345` 와 같은 방식으로 변경할 수 있어요

## 🛠️ 진행하다 어려웠던 부분에 대해서 작성 or 그런 부분을 어떻게 해결했는지 알려주세요!

N/A

## 📃 참고한 출처

- [SpringBoot 서버 포트 변경하기](https://jason-moon.tistory.com/104)

**Comment by khyojun** [comment]
@wjlee611 님 의견 감사합니다! 
나머지 질문에 대한 답변은 정말 잘해주셨는데요! 
1번항목과 같은 경우는 **왜? java11을 지원하지 않았을까요?**
