### ISSUE TITLE
[BE Tutorial] App 이웅재의 2장 생각해보기

### ISSUE THREAD

**Issue by wjlee611** [GDSC-Kwangwoon-University/BE-TUTORIAL#2]
## 🔍 생각해보기

1. url 상에서 사용되는 일종의 변수로, query parameter의 값에 따라 같은 url 이라도 다른 동작을 유도할 수 있어요
  `?qp1=value1&qp2=value2`와 같은 형태로 필드명과 데이터를 넘길 수 있어요
2. 같은 팀 내에서는 개발자들 간의 API 인터페이스와 진행상황을 공유하는데 사용할 수 있고,
  다른 팀들 간에는 개발을 병렬적으로 진행하기 위해 문서화를 해놓는 용도로 사용할 수 있어요
3. 로그인 정보, 쪽지 & 메일 숫자, 메인 페이지의 정보 등 여러 API를 호출하고 있어요
![스크린샷 2024-04-08 22 34 35](https://github.com/GDSC-Kwangwoon-University/BE-TUTORIAL/assets/66172061/4e0f8144-9e80-420d-b663-99aad8eefb61)

## 🛠️ 진행하다 어려웠던 부분에 대해서 작성 or 그런 부분을 어떻게 해결했는지 알려주세요!

Controller, Service (나아가 Repository(DAO))를 구분하는 기준을 알아보았습니다.

Spring boot 는 MVC(Model View Controller) 모델을 따른다고 합니다.
따라서 이 규격에 맞도록 레이어를 나누어둔게 위의 클래스 입니다.

- Controller
  웹 브라우저의 요청(API 엔드포인트)을 수신하는 레이어로, Mapper에 의해 수신부가 달라지는거 같습니다.
- Service
  Controller와 Repository 사이에 존재하는 레이어로, 대부분의 알고리즘적인 요소나 전처리 등 비즈니스 로직이 수행되는거 같습니다.
- Repository
  데이터베이스에 접근하는 레이어로, 비즈니스 로직에 필요한 쿼리를 호출하는 부분입니다.

중간중간에 DTO라는 용어도 등장하는데, DTO란 Data Transfer Object의 약자로 쉽게 말해 모델(Model)인 거 같습니다.

## 📃 참고한 출처

- [Spring boot - Controller, Service, DAO, Mapper](https://dalpaeng00.tistory.com/83)

**Comment by khyojun** [comment]
오오 너무 좋습니다! 잘 생각해주셨네요! 👍
